### ISSUE TITLE
how do i solve this issue "Warning: call_user_func() expects parameter 1 to be a valid callback, class 'RWMB_Group_Field' not found in /home/name/public_html/wp-content/plugins/meta-box/inc/meta-box.php on line 353"

### ISSUE THREAD

**Issue by trenovaltd** [humanmade/Custom-Meta-Boxes#320] opened 2016-02-18 16:15 UTC
i need assistance on how to solve the issue of error this on my website homepage Warning: call_user_func() expects parameter 1 to be a valid callback, class 'RWMB_Group_Field' not found in /home/dir/public_html/wp-content/plugins/meta-box/inc/meta-box.php on line 353

**Comment by barryceelen** [comment] 2016-02-18 20:59
The 'RWMB_Group_Field' class is part of the [Meta Box](https://metabox.io/) plugin. Support options for that plugin can be found [here](https://metabox.io/support/).

**Comment by mikeselander** [comment] 2016-07-04 18:48
Closing this issue as the problem is on another plugin.

**Closed by mikeselander** 2016-07-04 18:48 UTC
