### ISSUE TITLE
Using CMB on a theme

### ISSUE THREAD

**Issue by sefod** [humanmade/Custom-Meta-Boxes#261] opened 2014-09-13 04:47 UTC
I'm trying to use the CMB inside a theme, but I can see that CMB_URL constant is using plugins_url().

We replaced that with get_stylesheet_directory_uri(), and the framwork folder. Should I change that when I use it in a theme, or there is a better way to do it?

Thanks!

**Comment by mikeselander** [comment] 2017-01-03 13:51
Closing this as a duplicate of #226.

**Closed by mikeselander** 2017-01-03 13:51 UTC
Labels: Bug
