### ISSUE TITLE
Nested repeatable group

### ISSUE THREAD

**Issue by ramseyp** [humanmade/Custom-Meta-Boxes#36] opened 2013-03-14 06:51 UTC
Is it possible to have a repeatable group that contains within it, another repeatable group? Not to get too "Inception" here, but I have a project that could use such a thing. I didn't see any mention anywhere in the repo about this.

**Comment by mikeselander** [comment] 2017-01-03 14:12
Closing this issue as a duplicate of #64 since repeatable groups is now the outstanding issue

**Closed by mikeselander** 2017-01-03 14:12 UTC
Labels: Feature Request
